/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addCandidateSkill' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addEmploymentHistory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'addJobSkill' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'analyze' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createCandidate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'createJob' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'getCandidate' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getCandidates' : IDL.Func([], [IDL.Text], ['query']),
  'getJobs' : IDL.Func([], [IDL.Text], ['query']),
  'seedData' : IDL.Func([], [], []),
  'setGeminiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addCandidateSkill' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'addEmploymentHistory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'addJobSkill' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'analyze' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createCandidate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'createJob' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'getCandidate' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getCandidates' : IDL.Func([], [IDL.Text], ['query']),
    'getJobs' : IDL.Func([], [IDL.Text], ['query']),
    'seedData' : IDL.Func([], [], []),
    'setGeminiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };